# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"1\n\x08Greeting\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\"\xd2\x02\n\x10RequestCreateKey\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nusage_mask\x18\x02 \x01(\x05\x12\x11\n\talgorithm\x18\x03 \x01(\t\x12/\n\tmeta_info\x18\x04 \x03(\x0b\x32\x1c.greet.RequestCreateKey.meta\x12\r\n\x05state\x18\x05 \x01(\t\x12\x18\n\x10\x64\x65\x61\x63tivationDate\x18\x06 \x01(\t\x12\x17\n\x0fprotectStopDate\x18\x07 \x01(\t\x12\x35\n\x0c\x61liases_info\x18\x08 \x03(\x0b\x32\x1f.greet.RequestCreateKey.aliases\x12\r\n\x05label\x18\t \x01(\t\x12\x0e\n\x06label1\x18\n \x01(\t\x1a\x18\n\x04meta\x12\x10\n\x08owner_id\x18\x01 \x01(\t\x1a&\n\x07\x61liases\x12\r\n\x05\x61lias\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"\"\n\x0eReplyCreateKey\x12\x10\n\x08response\x18\x01 \x01(\t\"1\n\x0cGreetRequest\x12!\n\x08greeting\x18\x01 \x01(\x0b\x32\x0f.greet.Greeting\"\x1c\n\nGreetReply\x12\x0e\n\x06result\x18\x01 \x01(\t2\xb4\x02\n\x07Greeter\x12/\n\x05Greet\x12\x13.greet.GreetRequest\x1a\x11.greet.GreetReply\x12;\n\tCreateKey\x12\x17.greet.RequestCreateKey\x1a\x15.greet.ReplyCreateKey\x12@\n\x14GreetServerStreaming\x12\x13.greet.GreetRequest\x1a\x11.greet.GreetReply0\x01\x12@\n\x14GreetClientStreaming\x12\x13.greet.GreetRequest\x1a\x11.greet.GreetReply(\x01\x12\x37\n\tGreetBiDi\x12\x13.greet.GreetRequest\x1a\x11.greet.GreetReply(\x01\x30\x01\x62\x06proto3')



_GREETING = DESCRIPTOR.message_types_by_name['Greeting']
_REQUESTCREATEKEY = DESCRIPTOR.message_types_by_name['RequestCreateKey']
_REQUESTCREATEKEY_META = _REQUESTCREATEKEY.nested_types_by_name['meta']
_REQUESTCREATEKEY_ALIASES = _REQUESTCREATEKEY.nested_types_by_name['aliases']
_REPLYCREATEKEY = DESCRIPTOR.message_types_by_name['ReplyCreateKey']
_GREETREQUEST = DESCRIPTOR.message_types_by_name['GreetRequest']
_GREETREPLY = DESCRIPTOR.message_types_by_name['GreetReply']
Greeting = _reflection.GeneratedProtocolMessageType('Greeting', (_message.Message,), {
  'DESCRIPTOR' : _GREETING,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.Greeting)
  })
_sym_db.RegisterMessage(Greeting)

RequestCreateKey = _reflection.GeneratedProtocolMessageType('RequestCreateKey', (_message.Message,), {

  'meta' : _reflection.GeneratedProtocolMessageType('meta', (_message.Message,), {
    'DESCRIPTOR' : _REQUESTCREATEKEY_META,
    '__module__' : 'greet_pb2'
    # @@protoc_insertion_point(class_scope:greet.RequestCreateKey.meta)
    })
  ,

  'aliases' : _reflection.GeneratedProtocolMessageType('aliases', (_message.Message,), {
    'DESCRIPTOR' : _REQUESTCREATEKEY_ALIASES,
    '__module__' : 'greet_pb2'
    # @@protoc_insertion_point(class_scope:greet.RequestCreateKey.aliases)
    })
  ,
  'DESCRIPTOR' : _REQUESTCREATEKEY,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.RequestCreateKey)
  })
_sym_db.RegisterMessage(RequestCreateKey)
_sym_db.RegisterMessage(RequestCreateKey.meta)
_sym_db.RegisterMessage(RequestCreateKey.aliases)

ReplyCreateKey = _reflection.GeneratedProtocolMessageType('ReplyCreateKey', (_message.Message,), {
  'DESCRIPTOR' : _REPLYCREATEKEY,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.ReplyCreateKey)
  })
_sym_db.RegisterMessage(ReplyCreateKey)

GreetRequest = _reflection.GeneratedProtocolMessageType('GreetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETREQUEST,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetRequest)
  })
_sym_db.RegisterMessage(GreetRequest)

GreetReply = _reflection.GeneratedProtocolMessageType('GreetReply', (_message.Message,), {
  'DESCRIPTOR' : _GREETREPLY,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetReply)
  })
_sym_db.RegisterMessage(GreetReply)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GREETING._serialized_start=22
  _GREETING._serialized_end=71
  _REQUESTCREATEKEY._serialized_start=74
  _REQUESTCREATEKEY._serialized_end=412
  _REQUESTCREATEKEY_META._serialized_start=348
  _REQUESTCREATEKEY_META._serialized_end=372
  _REQUESTCREATEKEY_ALIASES._serialized_start=374
  _REQUESTCREATEKEY_ALIASES._serialized_end=412
  _REPLYCREATEKEY._serialized_start=414
  _REPLYCREATEKEY._serialized_end=448
  _GREETREQUEST._serialized_start=450
  _GREETREQUEST._serialized_end=499
  _GREETREPLY._serialized_start=501
  _GREETREPLY._serialized_end=529
  _GREETER._serialized_start=532
  _GREETER._serialized_end=840
# @@protoc_insertion_point(module_scope)
